#!/bin/bash

DIRS=`ls --time-style="long-iso"  -l ../aggregate_compiler | egrep '^d' | awk '{print $8}'`

echo "Switching to Branch"

git submodule foreach git checkout master 

echo ""
echo ""
echo "Pulling each submodule"
git submodule foreach git pull

echo ""
echo ""
echo "Pruning Non-Existent Remote Branches"
git submodule foreach git remote prune origin
