#!/bin/bash

DIRS=`ls --time-style="long-iso"  -l ../aggregate_compiler | egrep '^d' | awk '{print $8}'`

for DIR in $DIRS; do
	echo $DIR
	cd $DIR
	git checkout master
	git pull
	cd ..
	echo ""
done

